type: pal_locomotion::BipedDCMController
initial_state_machine_action: ""

dt: 0.0005
controller_dt: 0.002
estimator_dt: 0.001

starting_base_position: [0., 0., 1.2]

estimated_angular_velocity_scaling_gain: 1.0
estimated_linear_velocity_scaling_gain: 1.0
joint_velocity_scaling_gain: 1.0
global_torque_gain: 1.0

spawn_controller_thread: true
spawn_estimator_thread: true

imu_frame_name: imu_link
imu_name: base_imu

optimization_parameters:
  solver: "QpSimpleQPMAD"
