# Loads the imu information on top of the info in sensors.yaml
imu:
  kvh_imu:
    frame: kvh_imu_link

# Replaces the imu info in the controller_parameters_common.yaml
imu_frame_name: kvh_imu_link
imu_name: kvh_imu

# Replaces the imu information in estimator/kinematic_estimator_params.yaml
estimator_parameters:
  imu_link_frame_name: kvh_imu_link
  use_imu_filtered_angular_vel: false
  enable_bias_estimation: false
  freeze_foot_height: false
